---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thermostat-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAIE7UkO5FQmF+QVNJBPYZqORDGEEPKDT7juFNubEvkpjX+UT68ioPITYDnVJ6eZWAo79mqI/xzVTkBMWNWDl5WALIZr7nXNNUkfbGH4g1YZJPHBDSPc1ogU5PX2x4Kw99wNgoglvMl/llbiqC+tCYG7Z41Xdf62X55YhcHtPfEzHS4FXnhZ5QgooiA1X4e3BPHa7O6Ao/qUkd7fkBZrYieAMUIep8VUfrAn8iy96glAOXQTusFlxkPKnn7mzVs0ghFsmwvln9VTvg/stCeTF0ew+unztZxMYV9D4xxORzm/CuEVkIA8Ny6/VEq1wc4cffOyO35UTFV2+7QTZgAvrXlXB/puuG0/zg42mDSHPLdscnbQESKNizAtFDozgRCBDeu38l6sJZ8X6AkUMFgD4U9uo+hdqq2qIlgjvFBkG0UciXvqaRcH+cHD7fBZHOn5GweVy+jycypBuzL6pRqsVi9RbAEaRcQfvRsmlTJsCdCGrdxWNBL+ojk+zdKWM6Kcu8zNUkPvp9LTZggIFXg2BWb/Uqu1qF2m/At7wkxY7yoIYlj30cKc1XrNdDmj4BTJfngPBS4DW80J8lsoEfYXZ37wEHJoZO6ImvtbkJf7lYkjaGc3l77X7P3i2kA3zhdKU7EkHbAJmbZVmENkHz8Hq2tiZbj/VKKKOrIEBFNOHkwLI/285i7ZzWMqOj+CjsLxlc/8HjeQg/tEQ==
    username: AgBJILUjKTkqhaOnlIM913yW43g7d/xRfy8UdYDs8FnTvk/wk7SeypVQZH83Fo3bkkF6RA4jSBeCNx53cJ/uu4xugU/tOZpyCb2DFs7FhaF09eg14PDelKVd04EeYvVJro4lUwUg6wQ35aE5ZTKkYdSWgf8F91xGHf4LiZlFrObYmCmC3ejqwfV9yqWnhFYG/LYTbjamJn6/Gz95TZ6bPPUvW7bgn3eIhZCQyB7BNfDr/fG3t8+5mtDtoi7PTP5Rrdh++pWg36q/voiV7S9p3fPguDp3IYCHfisX/gkkvg2+VAMCgyqix6yjZ8sExXki01bFHg51dnQnNLEiHj4HuI0G/T9J8WX1ikZuJr7/zfd75cJCInKNDO5dnSp+hpjp1WLDRdNx6GrtQ3glTLofqhzT+iKpdM9LSxurpxNRVLU5tdr9lHBX1TzXqRE5T/tqeLe1drt0n4KwvL8lBhqrqThda3NnLtVCKQpiO4EtKkyDaCFNQuMW76222imfk2bVl23KrnA2o/B6ISq7fmLd3Uqu0ibJSm9ODThqJQX8JvnMK8INCQao4aMIRX/+Ve9G7E73Xmj30NmCQPFmScXGH+H1NnSKGyCLC2fP7sanCSUgbEm8L35drzdFogW+8dETeTiEZx8kA4kjiR6YMEpNDVKp5Ubd6o4Rbu6ekx7D7smelyd3eKNE/IKGNN8j8g68fzcgU3EO7lzUY4kSqLSyON8=
  template:
    metadata:
      name: thermostat-credentials
      namespace: monitoring
