---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oj-microline-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgA1RKh+rU4rCE7aWDKvTs0y2zXhVFBE0HmiYj0TRhtm0eB9jkatD8q4BZ+5bpZOGqPouDQPGE3GBModgY2y54cg5mRhz7KRXQjsN+cN3UIfS4IXlwPN/Usx7fzOwhTDxDDrFZO2cWCP/BqkcoY5vASOcHMYo23jUZPaTLDjS8d0yxp9MVp/32BvD1MA8B0E+hVaSEn9iqJYX/LXZ9pz3Fbr7i6tsbLNgYkHnzylmM0p4a5MfGwm0ePhgfMx7XxW/PIDNn1OKRMMye6SNPlQaedDyhfasNjuhEzWD/HRRcwhAEWMsSV93f656z655CVd+ZimsqJVbmzIq/WEl9GNAbuiMdGN+jsAbWqwm4fnree/o2T5DH9bVPSSE3UWiAXKfo/mJCadlA7lplfWCGxOSp9eAWvbV7kzt/bq8T/cYrlcawVhiEgFgVpnGx48wvGOpCoRVBj3sfguyUTAmitMFoX7nOHxZtA8m5zcNcdKrNmeO3+8zBF51oCNCnJ3+G5lfIg3L96rIuLIfIo1BYp+PP1TCZPzKEfsULJV6iysG49dQ8r2DIw/sKsqEcmXumt9uYoqIbech4RTPsm3NVawnBVUxcyG0x5Wl+xooEHrRex2RKjb+c71ap0ZDlV+y+wcVgFosdwiPwmUHEpEgx0Ma6vYYc6OZlPOr3jjIERI21pMO6YJTVFxiJTjyfL+3FihU9W24hJ1evsRMQ==
    username: AgAdsNEfi5qxMbqQ/S5GBrIC9u7+/blaVmpjbmmJZXowelSpFP/k4X8rxGVhtaPo5Eu3O8G6JxCuX529ad4fAh1pXOHMmpKk58IuhIR44Tl1LHwcJ1z1bX7UEc0SVR3g3nHE4yzH2z0AqryIHqmF1D+mO/2TorE9MbQWg4HxWkSp/ac7BgfwfgW6dAjPhoMiDVRKsL+xOx08GOP8KVReFXMxHQWRnfFqo42j8T9nBb4h7Fg5M2gF7dIJQ8+E6MYwQOUw130QMCJj4JbLEPvn6+NLcGRTd3284Kjh3gvQgAjUGkW237i0O4wmBMKjU9fRxcBvmeNjrEo1SqW93jvjn+uOslF3SZkCOmzuwANiESStpFxS9u8T9C4xgXoog1UEMTgQ0R3rb/eGctfxAuBKgvpphRli7m8fdMx6+xIZhSguY5fgf3a4dJvGDPKQ1nYkx9hHx6ZjlT/M6lWyaaF217eIcFkjC32N47nEKaZEWkJolA+ZDrNY3MXwkX+dw4jDUV2aDnd4kfWSbXadpCF326pxuzvooxWtz0htYuQXphonHc2rWsWlRXiiRGknR6BbwL6krR045AOO29qU6csi4hwMMlLHaUCZ+ZoSnEUh1SzyJdrK51PlBCoYqqgbeyDrvUi8PM0SpIgj54IfyDivz9TL5QDKY425PEnNiabF7i0s3tC/0SpnJxDh9xGsXSXgUJanyTlGdlgOjEA39VVHBd0=
  template:
    metadata:
      name: oj-microline-credentials
      namespace: monitoring
