apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thermostat
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: thermostat
  endpoints:
    - port: http
      path: /metrics/
      interval: 60s
